[package]
name = "rustviz-ui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pose-publisher = { path = "../pose-publisher" }
kiss3d = "0.31"
nalgebra = "0.26"
clap = "3.0.0-beta.4"
anyhow = "1.0"
